// packages/angular/src/html-authoring/element-picker.component.ts
import { Component } from '@angular/core';
import type { HtmlElementDefinition } from '@aurora/ui';
import { HtmlAuthoringService } from './authoring.service.js';

@Component({
  selector: 'aurora-html-element-picker',
  standalone: true,
  template: `
    @if (authoringService.isElementPickerOpen) {
      <div class="aurora-modal-overlay" (click)="close()">
        <div class="aurora-modal-container" (click)="$event.stopPropagation()">
          <!-- Header -->
          <div class="aurora-modal-header">
            <h3>🧩 All HTML Elements Picker</h3>
            <button type="button" class="aurora-close-btn" (click)="close()">✕</button>
          </div>

          <!-- Search Input -->
          <div class="aurora-picker-search">
            <input
              type="text"
              placeholder="Search elements by tag, name, aliases, or category (e.g., details, table, quote)..."
              [value]="searchQuery"
              (input)="onSearchInput($event)"
              autofocus
            />
          </div>

          <!-- Section Tabs -->
          <div class="aurora-picker-tabs">
            <button
              type="button"
              class="aurora-tab"
              [class.active]="activeTab === 'all'"
              (click)="setTab('all')"
            >
              Alphabetical ({{ allElements.length }})
            </button>
            <button
              type="button"
              class="aurora-tab"
              [class.active]="activeTab === 'suggested'"
              (click)="setTab('suggested')"
            >
              ★ Suggested for Context
            </button>
            <button
              type="button"
              class="aurora-tab"
              [class.active]="activeTab === 'favorites'"
              (click)="setTab('favorites')"
            >
              ♥ Favorites
            </button>
            <button
              type="button"
              class="aurora-tab"
              [class.active]="activeTab === 'recent'"
              (click)="setTab('recent')"
            >
              ⏱ Recently Used
            </button>
          </div>

          <!-- Elements Grid/List -->
          <div class="aurora-picker-body">
            @if (displayedElements.length === 0) {
              <div class="aurora-picker-empty">
                No matching HTML elements found.
              </div>
            }
            @for (def of displayedElements; track def.tagName) {
              <div
                class="aurora-picker-card"
                (click)="selectElement(def)"
              >
                <div class="aurora-card-top">
                  <span class="aurora-card-tag">&lt;{{ def.tagName }}&gt;</span>
                  <span class="aurora-card-cat">{{ def.category }}</span>
                  <button
                    type="button"
                    class="aurora-fav-toggle"
                    [class.favorited]="isFavorite(def.tagName)"
                    (click)="toggleFavorite($event, def.tagName)"
                    title="Toggle favorite"
                  >
                    ★
                  </button>
                </div>
                <div class="aurora-card-title">{{ def.displayName }}</div>
                <div class="aurora-card-desc">{{ def.description }}</div>
              </div>
            }
          </div>
        </div>
      </div>
    }
  `,
  styles: [`
    .aurora-modal-overlay {
      position: fixed;
      top: 0; left: 0; right: 0; bottom: 0;
      background: rgba(15, 23, 42, 0.6);
      backdrop-filter: blur(4px);
      z-index: 200000;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .aurora-modal-container {
      background: white;
      width: 720px;
      max-width: 92vw;
      max-height: 85vh;
      border-radius: 12px;
      box-shadow: 0 20px 25px -5px rgba(0,0,0,0.2);
      display: flex;
      flex-direction: column;
      overflow: hidden;
    }
    .aurora-modal-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 16px 20px;
      border-bottom: 1px solid #e2e8f0;
    }
    .aurora-modal-header h3 {
      margin: 0;
      font-size: 18px;
      color: #0f172a;
    }
    .aurora-close-btn {
      border: none;
      background: transparent;
      font-size: 18px;
      cursor: pointer;
      color: #64748b;
    }
    .aurora-picker-search {
      padding: 12px 20px;
      border-bottom: 1px solid #e2e8f0;
    }
    .aurora-picker-search input {
      width: 100%;
      padding: 10px 14px;
      border: 1px solid #cbd5e1;
      border-radius: 8px;
      font-size: 14px;
      outline: none;
      box-sizing: border-box;
    }
    .aurora-picker-search input:focus {
      border-color: #6366f1;
      box-shadow: 0 0 0 3px rgba(99, 102, 241, 0.15);
    }
    .aurora-picker-tabs {
      display: flex;
      padding: 8px 20px;
      background: #f8fafc;
      border-bottom: 1px solid #e2e8f0;
      gap: 8px;
    }
    .aurora-tab {
      border: 1px solid transparent;
      background: transparent;
      padding: 6px 12px;
      border-radius: 6px;
      font-size: 13px;
      cursor: pointer;
      color: #475569;
    }
    .aurora-tab.active {
      background: white;
      border-color: #cbd5e1;
      font-weight: 600;
      color: #0f172a;
    }
    .aurora-picker-body {
      padding: 16px 20px;
      overflow-y: auto;
      display: grid;
      grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
      gap: 12px;
      max-height: 50vh;
    }
    .aurora-picker-card {
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 12px;
      cursor: pointer;
      transition: all 0.15s ease;
      background: #ffffff;
      display: flex;
      flex-direction: column;
    }
    .aurora-picker-card:hover {
      border-color: #6366f1;
      transform: translateY(-1px);
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
    }
    .aurora-card-top {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 6px;
    }
    .aurora-card-tag {
      font-family: monospace;
      font-size: 12px;
      font-weight: bold;
      color: #6366f1;
    }
    .aurora-card-cat {
      font-size: 10px;
      padding: 2px 6px;
      border-radius: 4px;
      background: #f1f5f9;
      color: #475569;
      text-transform: uppercase;
    }
    .aurora-fav-toggle {
      border: none;
      background: transparent;
      color: #cbd5e1;
      cursor: pointer;
      font-size: 14px;
    }
    .aurora-fav-toggle.favorited {
      color: #eab308;
    }
    .aurora-card-title {
      font-size: 13px;
      font-weight: 600;
      color: #1e293b;
      margin-bottom: 4px;
    }
    .aurora-card-desc {
      font-size: 11px;
      color: #64748b;
      line-height: 1.4;
    }
    .aurora-picker-empty {
      grid-column: 1 / -1;
      text-align: center;
      padding: 40px;
      color: #64748b;
    }
  `]
})
export class AuroraHtmlElementPickerComponent {
  public searchQuery = '';
  public activeTab: 'all' | 'suggested' | 'favorites' | 'recent' = 'all';

  constructor(public authoringService: HtmlAuthoringService) {}

  get allElements(): HtmlElementDefinition[] {
    return this.authoringService.getRegistry().getAll();
  }

  get displayedElements(): HtmlElementDefinition[] {
    const registry = this.authoringService.getRegistry();

    if (this.searchQuery.trim()) {
      return registry.search(this.searchQuery);
    }

    if (this.activeTab === 'favorites') {
      const favs = this.authoringService.getFavorites();
      return favs.map((t) => registry.get(t)).filter((d): d is HtmlElementDefinition => !!d);
    }

    if (this.activeTab === 'recent') {
      const recents = this.authoringService.getRecentElements();
      return recents.map((t) => registry.get(t)).filter((d): d is HtmlElementDefinition => !!d);
    }

    if (this.activeTab === 'suggested') {
      return this.authoringService.getAvailableElements().sort((a, b) => {
        const scoreA = this.authoringService.evaluateElement(a).score;
        const scoreB = this.authoringService.evaluateElement(b).score;
        return scoreB - scoreA;
      });
    }

    return [...this.allElements].sort((a, b) => a.tagName.localeCompare(b.tagName));
  }

  setTab(tab: 'all' | 'suggested' | 'favorites' | 'recent'): void {
    this.activeTab = tab;
  }

  onSearchInput(event: Event): void {
    this.searchQuery = (event.target as HTMLInputElement).value;
  }

  close(): void {
    this.authoringService.isElementPickerOpen = false;
  }

  selectElement(def: HtmlElementDefinition): void {
    this.authoringService.insert(def);
    this.close();
  }

  isFavorite(tagName: string): boolean {
    return this.authoringService.getFavorites().includes(tagName.toLowerCase());
  }

  toggleFavorite(event: Event, tagName: string): void {
    event.stopPropagation();
    this.authoringService.toggleFavorite(tagName);
  }
}

// packages/react/src/html-authoring/element-picker.tsx
import { useState, useMemo } from 'react';
import type { HtmlElementDefinition } from '@aurora/ui';
import { useAurora } from './context.js';

export function AuroraHtmlElementPicker() {
  const {
    isElementPickerOpen,
    setElementPickerOpen,
    registry,
    insert,
    evaluateElement,
    toggleFavorite,
    getFavorites,
    getRecentElements,
    context
  } = useAurora();

  const [searchQuery, setSearchQuery] = useState('');
  const [activeTab, setActiveTab] = useState<'all' | 'suggested' | 'favorites' | 'recent'>('all');

  const allElements = useMemo(() => registry.getAll(), [registry]);

  const displayedElements = useMemo(() => {
    if (searchQuery.trim()) {
      return registry.search(searchQuery);
    }

    if (activeTab === 'favorites') {
      const favs = getFavorites();
      return favs.map((t) => registry.get(t)).filter((d): d is HtmlElementDefinition => !!d);
    }

    if (activeTab === 'recent') {
      const recents = getRecentElements();
      return recents.map((t) => registry.get(t)).filter((d): d is HtmlElementDefinition => !!d);
    }

    if (activeTab === 'suggested') {
      return registry.getAvailable(context).sort((a, b) => {
        const scoreA = evaluateElement(a).score;
        const scoreB = evaluateElement(b).score;
        return scoreB - scoreA;
      });
    }

    return [...allElements].sort((a, b) => a.tagName.localeCompare(b.tagName));
  }, [searchQuery, activeTab, registry, getFavorites, getRecentElements, context, evaluateElement, allElements]);

  if (!isElementPickerOpen) return null;

  const close = () => setElementPickerOpen(false);

  const select = (def: HtmlElementDefinition) => {
    insert(def);
    close();
  };

  const isFav = (tag: string) => getFavorites().includes(tag.toLowerCase());

  return (
    <div
      className="aurora-modal-overlay"
      style={{
        position: 'fixed',
        top: 0, left: 0, right: 0, bottom: 0,
        background: 'rgba(15, 23, 42, 0.6)',
        backdropFilter: 'blur(4px)',
        zIndex: 200000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
      }}
      onClick={close}
    >
      <div
        className="aurora-modal-container"
        style={{
          background: 'white',
          width: '720px',
          maxWidth: '92vw',
          maxHeight: '85vh',
          borderRadius: '12px',
          boxShadow: '0 20px 25px -5px rgba(0,0,0,0.2)',
          display: 'flex',
          flexDirection: 'column',
          overflow: 'hidden'
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '16px 20px',
          borderBottom: '1px solid #e2e8f0'
        }}>
          <h3 style={{ margin: 0, fontSize: '18px', color: '#0f172a' }}>
            🧩 All HTML Elements Picker
          </h3>
          <button
            type="button"
            style={{ border: 'none', background: 'transparent', fontSize: '18px', cursor: 'pointer', color: '#64748b' }}
            onClick={close}
          >
            ✕
          </button>
        </div>

        {/* Search Input */}
        <div style={{ padding: '12px 20px', borderBottom: '1px solid #e2e8f0' }}>
          <input
            type="text"
            placeholder="Search elements by tag, name, aliases, or category (e.g., details, table, quote)..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            style={{
              width: '100%',
              padding: '10px 14px',
              border: '1px solid #cbd5e1',
              borderRadius: '8px',
              fontSize: '14px',
              outline: 'none',
              boxSizing: 'border-box'
            }}
            autoFocus
          />
        </div>

        {/* Section Tabs */}
        <div style={{ display: 'flex', padding: '8px 20px', background: '#f8fafc', borderBottom: '1px solid #e2e8f0', gap: '8px' }}>
          {(['all', 'suggested', 'favorites', 'recent'] as const).map((tab) => (
            <button
              key={tab}
              type="button"
              style={{
                border: '1px solid transparent',
                background: activeTab === tab ? 'white' : 'transparent',
                borderColor: activeTab === tab ? '#cbd5e1' : 'transparent',
                fontWeight: activeTab === tab ? 600 : 'normal',
                padding: '6px 12px',
                borderRadius: '6px',
                fontSize: '13px',
                cursor: 'pointer',
                color: activeTab === tab ? '#0f172a' : '#475569'
              }}
              onClick={() => setActiveTab(tab)}
            >
              {tab === 'all' && `Alphabetical (${allElements.length})`}
              {tab === 'suggested' && '★ Suggested for Context'}
              {tab === 'favorites' && '♥ Favorites'}
              {tab === 'recent' && '⏱ Recently Used'}
            </button>
          ))}
        </div>

        {/* Elements Grid */}
        <div style={{
          padding: '16px 20px',
          overflowY: 'auto',
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
          gap: '12px',
          maxHeight: '50vh'
        }}>
          {displayedElements.length === 0 && (
            <div style={{ gridColumn: '1 / -1', textAlign: 'center', padding: '40px', color: '#64748b' }}>
              No matching HTML elements found.
            </div>
          )}
          {displayedElements.map((def) => (
            <div
              key={def.tagName}
              style={{
                border: '1px solid #e2e8f0',
                borderRadius: '8px',
                padding: '12px',
                cursor: 'pointer',
                background: '#ffffff',
                display: 'flex',
                flexDirection: 'column'
              }}
              onClick={() => select(def)}
            >
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                <span style={{ fontFamily: 'monospace', fontSize: '12px', fontWeight: 'bold', color: '#6366f1' }}>
                  &lt;{def.tagName}&gt;
                </span>
                <span style={{ fontSize: '10px', padding: '2px 6px', borderRadius: '4px', background: '#f1f5f9', color: '#475569', textTransform: 'uppercase' }}>
                  {def.category}
                </span>
                <button
                  type="button"
                  style={{
                    border: 'none',
                    background: 'transparent',
                    color: isFav(def.tagName) ? '#eab308' : '#cbd5e1',
                    cursor: 'pointer',
                    fontSize: '14px'
                  }}
                  onClick={(e) => {
                    e.stopPropagation();
                    toggleFavorite(def.tagName);
                  }}
                >
                  ★
                </button>
              </div>
              <div style={{ fontSize: '13px', fontWeight: 600, color: '#1e293b', marginBottom: '4px' }}>
                {def.displayName}
              </div>
              <div style={{ fontSize: '11px', color: '#64748b', lineHeight: 1.4 }}>
                {def.description}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
