// packages/angular/src/html-authoring/insert-menu.component.ts
import { Component } from '@angular/core';
import type { ElementCategory, HtmlElementDefinition } from '@aurora/ui';
import { HtmlAuthoringService } from './authoring.service.js';

@Component({
  selector: 'aurora-insert-menu',
  standalone: true,
  template: `
    <div class="aurora-insert-menu-dropdown">
      <div class="aurora-insert-menu-categories">
        @for (cat of categories; track cat) {
          <button
            type="button"
            class="aurora-category-tab"
            [class.active]="selectedCategory === cat"
            (click)="selectCategory(cat)"
          >
            {{ formatCategory(cat) }}
          </button>
        }
      </div>

      <div class="aurora-insert-menu-items">
        @if (items.length === 0) {
          <div class="aurora-empty-state">
            No elements available in this category
          </div>
        }
        @for (def of items; track def.tagName) {
          <button
            type="button"
            class="aurora-insert-item"
            (click)="insertElement(def)"
          >
            <span class="aurora-item-tag">&lt;{{ def.tagName }}&gt;</span>
            <span class="aurora-item-name">{{ def.displayName }}</span>
            <span class="aurora-item-desc">{{ def.description }}</span>
          </button>
        }
      </div>
    </div>
  `,
  styles: [`
    .aurora-insert-menu-dropdown {
      display: flex;
      background: white;
      border: 1px solid #cbd5e1;
      border-radius: 8px;
      box-shadow: 0 10px 25px rgba(0,0,0,0.1);
      width: 480px;
      max-height: 400px;
      overflow: hidden;
    }
    .aurora-insert-menu-categories {
      width: 140px;
      background: #f8fafc;
      border-right: 1px solid #e2e8f0;
      padding: 6px;
      display: flex;
      flex-direction: column;
      gap: 2px;
    }
    .aurora-category-tab {
      border: none;
      background: transparent;
      padding: 8px 10px;
      border-radius: 6px;
      text-align: left;
      font-size: 13px;
      cursor: pointer;
      color: #334155;
    }
    .aurora-category-tab.active, .aurora-category-tab:hover {
      background: #e2e8f0;
      font-weight: 600;
      color: #0f172a;
    }
    .aurora-insert-menu-items {
      flex: 1;
      padding: 8px;
      overflow-y: auto;
      display: flex;
      flex-direction: column;
      gap: 4px;
    }
    .aurora-insert-item {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      padding: 8px 10px;
      border: 1px solid transparent;
      border-radius: 6px;
      background: transparent;
      text-align: left;
      cursor: pointer;
    }
    .aurora-insert-item:hover {
      background: #f1f5f9;
      border-color: #cbd5e1;
    }
    .aurora-item-tag {
      font-family: monospace;
      font-size: 11px;
      color: #6366f1;
      font-weight: 600;
    }
    .aurora-item-name {
      font-size: 13px;
      font-weight: 600;
      color: #1e293b;
    }
    .aurora-item-desc {
      font-size: 11px;
      color: #64748b;
    }
  `]
})
export class AuroraInsertMenuComponent {
  public categories: ElementCategory[] = [
    'basic',
    'text',
    'heading',
    'structure',
    'lists',
    'links',
    'media',
    'tables',
    'forms',
    'interactive',
    'data-code',
    'custom'
  ];

  public selectedCategory: ElementCategory = 'basic';

  constructor(private authoringService: HtmlAuthoringService) {}

  get items(): HtmlElementDefinition[] {
    return this.authoringService.getRegistry().getByCategory(this.selectedCategory);
  }

  selectCategory(cat: ElementCategory): void {
    this.selectedCategory = cat;
  }

  formatCategory(cat: string): string {
    return cat.charAt(0).toUpperCase() + cat.slice(1).replace('-', ' ');
  }

  insertElement(def: HtmlElementDefinition): void {
    this.authoringService.insert(def);
  }
}

// packages/react/src/html-authoring/insert-menu.tsx
import { useState } from 'react';
import type { ElementCategory } from '@aurora/ui';
import { useAurora } from './context.js';

const CATEGORIES: ElementCategory[] = [
  'basic',
  'text',
  'heading',
  'structure',
  'lists',
  'links',
  'media',
  'tables',
  'forms',
  'interactive',
  'data-code',
  'custom'
];

export function AuroraInsertMenu() {
  const { registry, insert } = useAurora();
  const [selectedCategory, setSelectedCategory] = useState<ElementCategory>('basic');

  const items = registry.getByCategory(selectedCategory);

  const formatCategory = (cat: string) => {
    return cat.charAt(0).toUpperCase() + cat.slice(1).replace('-', ' ');
  };

  return (
    <div className="aurora-react-insert-menu-dropdown" style={{
      display: 'flex',
      background: 'white',
      border: '1px solid #cbd5e1',
      borderRadius: '8px',
      boxShadow: '0 10px 25px rgba(0,0,0,0.1)',
      width: '480px',
      maxHeight: '400px',
      overflow: 'hidden'
    }}>
      <div className="aurora-insert-menu-categories" style={{
        width: '140px',
        background: '#f8fafc',
        borderRight: '1px solid #e2e8f0',
        padding: '6px',
        display: 'flex',
        flexDirection: 'column',
        gap: '2px'
      }}>
        {CATEGORIES.map((cat) => (
          <button
            key={cat}
            type="button"
            className={`aurora-category-tab ${selectedCategory === cat ? 'active' : ''}`}
            style={{
              border: 'none',
              background: selectedCategory === cat ? '#e2e8f0' : 'transparent',
              fontWeight: selectedCategory === cat ? 600 : 'normal',
              padding: '8px 10px',
              borderRadius: '6px',
              textAlign: 'left',
              fontSize: '13px',
              cursor: 'pointer',
              color: selectedCategory === cat ? '#0f172a' : '#334155'
            }}
            onClick={() => setSelectedCategory(cat)}
          >
            {formatCategory(cat)}
          </button>
        ))}
      </div>

      <div className="aurora-insert-menu-items" style={{
        flex: 1,
        padding: '8px',
        overflowY: 'auto',
        display: 'flex',
        flexDirection: 'column',
        gap: '4px'
      }}>
        {items.length === 0 && (
          <div style={{ padding: '20px', textAlign: 'center', color: '#64748b' }}>
            No elements available in this category
          </div>
        )}
        {items.map((def) => (
          <button
            key={def.tagName}
            type="button"
            className="aurora-insert-item"
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'flex-start',
              padding: '8px 10px',
              border: '1px solid transparent',
              borderRadius: '6px',
              background: 'transparent',
              textAlign: 'left',
              cursor: 'pointer'
            }}
            onClick={() => insert(def)}
          >
            <span style={{ fontFamily: 'monospace', fontSize: '11px', color: '#6366f1', fontWeight: 'bold' }}>
              &lt;{def.tagName}&gt;
            </span>
            <span style={{ fontSize: '13px', fontWeight: 600, color: '#1e293b' }}>
              {def.displayName}
            </span>
            <span style={{ fontSize: '11px', color: '#64748b' }}>
              {def.description}
            </span>
          </button>
        ))}
      </div>
    </div>
  );
}
