// packages/angular/src/html-authoring/toolbar.component.ts
import { Component, Input, OnInit, OnDestroy, ElementRef } from '@angular/core';
import type { AuroraEditor } from '@aurora/editor';
import {
  calculateToolbarLayout,
  type ResponsiveCommandMetadata,
  type ResponsiveBreakpoint
} from '@aurora/ui';
import { HtmlAuthoringService } from './authoring.service.js';

@Component({
  selector: 'aurora-rte-toolbar',
  standalone: true,
  template: `
    <div class="aurora-rte-toolbar-wrapper" [class]="'aurora-bp-' + currentBreakpoint">
      <!-- Main Action Bar -->
      <div class="aurora-rte-toolbar" role="toolbar" aria-label="Editor Formatting Toolbar">
        <!-- Essential actions -->
        <button type="button" class="aurora-tb-btn" (click)="exec('undo')" title="Undo (Ctrl+Z)">↩</button>
        <button type="button" class="aurora-tb-btn" (click)="exec('redo')" title="Redo (Ctrl+Y)">↪</button>
        <div class="aurora-tb-sep"></div>

        <button type="button" class="aurora-tb-btn" (click)="exec('toggleBold')" title="Bold (Ctrl+B)"><b>B</b></button>
        <button type="button" class="aurora-tb-btn" (click)="exec('toggleItalic')" title="Italic (Ctrl+I)"><i>I</i></button>
        <button type="button" class="aurora-tb-btn" (click)="exec('toggleUnderline')" title="Underline (Ctrl+U)"><u>U</u></button>
        <button type="button" class="aurora-tb-btn" (click)="exec('toggleStrike')" title="Strikethrough"><s>S</s></button>
        <div class="aurora-tb-sep"></div>

        <!-- Headings & Structure -->
        @if (isCommandVisible('h1')) {
          <button type="button" class="aurora-tb-btn" (click)="exec('setHeading', { level: 1 })">H1</button>
        }
        @if (isCommandVisible('h2')) {
          <button type="button" class="aurora-tb-btn" (click)="exec('setHeading', { level: 2 })">H2</button>
        }
        @if (isCommandVisible('h3')) {
          <button type="button" class="aurora-tb-btn" (click)="exec('setHeading', { level: 3 })">H3</button>
        }

        <!-- Lists -->
        @if (isCommandVisible('bullet-list')) {
          <button type="button" class="aurora-tb-btn" (click)="exec('toggleBulletList')" title="Bullet List">•≡</button>
        }
        @if (isCommandVisible('ordered-list')) {
          <button type="button" class="aurora-tb-btn" (click)="exec('toggleOrderedList')" title="Numbered List">1≡</button>
        }

        <!-- Table & Media -->
        @if (isCommandVisible('table')) {
          <button type="button" class="aurora-tb-btn" (click)="exec('insertTable', { rows: 3, columns: 3 })" title="Insert Table">▦</button>
        }
        @if (isCommandVisible('quote')) {
          <button type="button" class="aurora-tb-btn" (click)="exec('toggleBlockquote')" title="Quote">❝</button>
        }
        @if (isCommandVisible('code')) {
          <button type="button" class="aurora-tb-btn" (click)="exec('toggleCodeBlock')" title="Code Block">&lt;/&gt;</button>
        }

        <div class="aurora-tb-sep"></div>

        <!-- Tools / Modal Launchers -->
        <button type="button" class="aurora-tb-btn aurora-tb-picker-btn" (click)="openPicker()" title="All HTML Elements Picker">
          🧩 Elements...
        </button>
        <button type="button" class="aurora-tb-btn" (click)="openPalette()" title="Command Palette (Ctrl+K)">
          ⌘K
        </button>

        <!-- Overflow Button -->
        @if (overflowCommands.length > 0) {
          <div class="aurora-tb-overflow-container">
            <button type="button" class="aurora-tb-btn aurora-tb-overflow-btn" (click)="toggleOverflow()">
              •••
            </button>
            @if (isOverflowOpen) {
              <div class="aurora-tb-overflow-dropdown">
                @for (cmdId of overflowCommands; track cmdId) {
                  <button type="button" class="aurora-dropdown-item" (click)="execOverflow(cmdId)">
                    {{ cmdId }}
                  </button>
                }
              </div>
            }
          </div>
        }
      </div>
    </div>
  `,
  styles: [`
    .aurora-rte-toolbar-wrapper {
      display: flex;
      width: 100%;
      border-bottom: 1px solid var(--aurora-border, #e2e8f0);
      background: var(--aurora-bg, #ffffff);
    }
    .aurora-rte-toolbar {
      display: flex;
      align-items: center;
      gap: 4px;
      padding: 6px 10px;
      overflow-x: auto;
      width: 100%;
    }
    .aurora-tb-btn {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      height: 32px;
      min-width: 32px;
      padding: 0 8px;
      border: 1px solid transparent;
      border-radius: 4px;
      background: transparent;
      color: inherit;
      cursor: pointer;
      font-size: 14px;
    }
    .aurora-tb-btn:hover {
      background: var(--aurora-btn-hover, #f1f5f9);
    }
    .aurora-tb-sep {
      width: 1px;
      height: 20px;
      background: var(--aurora-border, #e2e8f0);
      margin: 0 4px;
    }
    .aurora-tb-overflow-container {
      position: relative;
      margin-left: auto;
    }
    .aurora-tb-overflow-dropdown {
      position: absolute;
      top: 100%;
      right: 0;
      background: white;
      border: 1px solid #cbd5e1;
      border-radius: 6px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.1);
      z-index: 1000;
      min-width: 160px;
      padding: 4px 0;
    }
    .aurora-dropdown-item {
      display: block;
      width: 100%;
      padding: 8px 12px;
      border: none;
      background: transparent;
      text-align: left;
      cursor: pointer;
    }
    .aurora-dropdown-item:hover {
      background: #f1f5f9;
    }
  `]
})
export class AuroraRteToolbarComponent implements OnInit, OnDestroy {
  @Input() editor?: AuroraEditor;

  public currentBreakpoint: ResponsiveBreakpoint = 'standard';
  public isOverflowOpen = false;
  public visibleCommands: string[] = [];
  public overflowCommands: string[] = [];

  private resizeObserver: ResizeObserver | null = null;

  private allCommands: ResponsiveCommandMetadata[] = [
    { id: 'h1', priority: 1, estimatedWidth: 40, preferredSurface: 'toolbar' },
    { id: 'h2', priority: 2, estimatedWidth: 40, preferredSurface: 'toolbar' },
    { id: 'h3', priority: 3, estimatedWidth: 40, preferredSurface: 'toolbar' },
    { id: 'bullet-list', priority: 2, estimatedWidth: 40, preferredSurface: 'toolbar' },
    { id: 'ordered-list', priority: 3, estimatedWidth: 40, preferredSurface: 'toolbar' },
    { id: 'table', priority: 2, estimatedWidth: 40, preferredSurface: 'toolbar' },
    { id: 'quote', priority: 4, estimatedWidth: 40, preferredSurface: 'toolbar' },
    { id: 'code', priority: 4, estimatedWidth: 40, preferredSurface: 'toolbar' }
  ];

  constructor(
    private el: ElementRef<HTMLElement>,
    private authoringService: HtmlAuthoringService
  ) {}

  ngOnInit() {
    this.updateLayout(this.el.nativeElement.clientWidth || 1000);

    if (typeof ResizeObserver !== 'undefined') {
      this.resizeObserver = new ResizeObserver((entries) => {
        for (const entry of entries) {
          const w = entry.contentRect.width;
          this.updateLayout(w);
        }
      });
      this.resizeObserver.observe(this.el.nativeElement);
    }
  }

  ngOnDestroy() {
    this.resizeObserver?.disconnect();
  }

  private updateLayout(width: number) {
    const plan = calculateToolbarLayout(width, this.allCommands);
    this.currentBreakpoint = plan.breakpoint;
    this.visibleCommands = plan.visibleCommandIds;
    this.overflowCommands = plan.overflowCommandIds;
  }

  isCommandVisible(id: string): boolean {
    return this.visibleCommands.includes(id);
  }

  toggleOverflow(): void {
    this.isOverflowOpen = !this.isOverflowOpen;
  }

  exec(commandName: string, input?: unknown): void {
    const activeEditor = this.editor || this.authoringService.getEditor();
    if (activeEditor) {
      activeEditor.execute(commandName, input);
    }
  }

  execOverflow(cmdId: string): void {
    this.isOverflowOpen = false;
    this.exec(cmdId);
  }

  openPicker(): void {
    this.authoringService.isElementPickerOpen = true;
  }

  openPalette(): void {
    this.authoringService.isCommandPaletteOpen = true;
  }
}

// packages/react/src/html-authoring/toolbar.tsx
import { useState, useEffect, useRef, type CSSProperties } from 'react';
import { calculateToolbarLayout, type ResponsiveCommandMetadata, type ResponsiveBreakpoint } from '@aurora/ui';
import { useAurora } from './context.js';

const ALL_COMMANDS: ResponsiveCommandMetadata[] = [
  { id: 'h1', priority: 1, estimatedWidth: 40, preferredSurface: 'toolbar' },
  { id: 'h2', priority: 2, estimatedWidth: 40, preferredSurface: 'toolbar' },
  { id: 'h3', priority: 3, estimatedWidth: 40, preferredSurface: 'toolbar' },
  { id: 'bullet-list', priority: 2, estimatedWidth: 40, preferredSurface: 'toolbar' },
  { id: 'ordered-list', priority: 3, estimatedWidth: 40, preferredSurface: 'toolbar' },
  { id: 'table', priority: 2, estimatedWidth: 40, preferredSurface: 'toolbar' },
  { id: 'quote', priority: 4, estimatedWidth: 40, preferredSurface: 'toolbar' },
  { id: 'code', priority: 4, estimatedWidth: 40, preferredSurface: 'toolbar' }
];

const REACT_TOOLBAR_STYLES = `
  .aurora-react-toolbar-wrapper {
    display: flex;
    width: 100%;
    margin-bottom: 10px;
  }
  .aurora-react-toolbar {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 4px;
    padding: 6px 10px;
    width: 100%;
    background: var(--aurora-muted-bg, rgba(255, 255, 255, 0.04));
    border: 1px solid var(--aurora-border, #132a59);
    border-radius: 8px;
    box-sizing: border-box;
  }
  .aurora-tb-btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: 32px;
    height: 32px;
    padding: 0 8px;
    border: 1px solid transparent;
    border-radius: 5px;
    background: transparent;
    color: var(--aurora-fg, #f0f4f8);
    font-size: 13px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.15s ease;
    user-select: none;
    box-sizing: border-box;
  }
  .aurora-tb-btn:hover {
    background: rgba(40, 230, 245, 0.12);
    border-color: var(--aurora-border, rgba(40, 230, 245, 0.3));
    color: var(--aurora-primary, #28E6F5);
  }
  .aurora-tb-btn:active {
    transform: scale(0.96);
  }
  .aurora-tb-btn.is-active {
    background: var(--aurora-primary, #28E6F5);
    color: #040d21;
    border-color: var(--aurora-primary, #28E6F5);
  }
  .aurora-tb-sep {
    width: 1px;
    height: 20px;
    background: var(--aurora-border, #132a59);
    margin: 0 4px;
  }
  .aurora-tb-picker-btn {
    color: var(--aurora-primary, #28E6F5);
    border-color: var(--aurora-border, #132a59);
    background: rgba(40, 230, 245, 0.08);
  }
`;

function ensureReactToolbarStyles() {
  if (typeof document === 'undefined') return;
  if (document.getElementById('aurora-react-toolbar-styles')) return;

  const styleEl = document.createElement('style');
  styleEl.id = 'aurora-react-toolbar-styles';
  styleEl.textContent = REACT_TOOLBAR_STYLES;
  document.head.appendChild(styleEl);
}

export interface AuroraToolbarProps {
  className?: string;
  style?: CSSProperties;
}

export function AuroraToolbar({ className = '', style }: AuroraToolbarProps) {
  ensureReactToolbarStyles();
  const { editor, setElementPickerOpen, setCommandPaletteOpen } = useAurora();
  const containerRef = useRef<HTMLDivElement>(null);
  const [breakpoint, setBreakpoint] = useState<ResponsiveBreakpoint>('standard');
  const [visibleCommands, setVisibleCommands] = useState<string[]>([]);
  const [overflowCommands, setOverflowCommands] = useState<string[]>([]);
  const [isOverflowOpen, setIsOverflowOpen] = useState(false);

  useEffect(() => {
    if (!containerRef.current) return undefined;

    const update = (width: number) => {
      const plan = calculateToolbarLayout(width, ALL_COMMANDS);
      setBreakpoint(plan.breakpoint);
      setVisibleCommands(plan.visibleCommandIds);
      setOverflowCommands(plan.overflowCommandIds);
    };

    update(containerRef.current.clientWidth || 1000);

    if (typeof ResizeObserver !== 'undefined') {
      const observer = new ResizeObserver((entries) => {
        for (const entry of entries) {
          update(entry.contentRect.width);
        }
      });
      observer.observe(containerRef.current);
      return () => observer.disconnect();
    }
    return undefined;
  }, []);

  const exec = (cmd: string, input?: unknown) => {
    editor?.execute(cmd, input);
  };

  const isCommandVisible = (id: string) => visibleCommands.includes(id);

  return (
    <div
      ref={containerRef}
      className={`aurora-react-toolbar-wrapper aurora-bp-${breakpoint} ${className}`.trim()}
      style={style}
    >
      <div className="aurora-react-toolbar" role="toolbar" aria-label="React Editor Formatting Toolbar">
        <button type="button" className="aurora-tb-btn" onClick={() => exec('undo')} title="Undo (Ctrl+Z)">↩</button>
        <button type="button" className="aurora-tb-btn" onClick={() => exec('redo')} title="Redo (Ctrl+Y)">↪</button>
        <div className="aurora-tb-sep" />

        <button type="button" className="aurora-tb-btn" onClick={() => exec('toggleBold')} title="Bold (Ctrl+B)"><b>B</b></button>
        <button type="button" className="aurora-tb-btn" onClick={() => exec('toggleItalic')} title="Italic (Ctrl+I)"><i>I</i></button>
        <button type="button" className="aurora-tb-btn" onClick={() => exec('toggleUnderline')} title="Underline (Ctrl+U)"><u>U</u></button>
        <button type="button" className="aurora-tb-btn" onClick={() => exec('toggleStrike')} title="Strikethrough"><s>S</s></button>
        <div className="aurora-tb-sep" />

        {isCommandVisible('h1') && (
          <button type="button" className="aurora-tb-btn" onClick={() => exec('setHeading', { level: 1 })}>H1</button>
        )}
        {isCommandVisible('h2') && (
          <button type="button" className="aurora-tb-btn" onClick={() => exec('setHeading', { level: 2 })}>H2</button>
        )}
        {isCommandVisible('h3') && (
          <button type="button" className="aurora-tb-btn" onClick={() => exec('setHeading', { level: 3 })}>H3</button>
        )}

        {isCommandVisible('bullet-list') && (
          <button type="button" className="aurora-tb-btn" onClick={() => exec('toggleBulletList')} title="Bullet List">•≡</button>
        )}
        {isCommandVisible('ordered-list') && (
          <button type="button" className="aurora-tb-btn" onClick={() => exec('toggleOrderedList')} title="Numbered List">1≡</button>
        )}

        {isCommandVisible('table') && (
          <button type="button" className="aurora-tb-btn" onClick={() => exec('insertTable', { rows: 3, columns: 3 })} title="Insert Table">▦</button>
        )}
        {isCommandVisible('quote') && (
          <button type="button" className="aurora-tb-btn" onClick={() => exec('toggleBlockquote')} title="Quote">❝</button>
        )}
        {isCommandVisible('code') && (
          <button type="button" className="aurora-tb-btn" onClick={() => exec('toggleCodeBlock')} title="Code Block">&lt;/&gt;</button>
        )}

        <div className="aurora-tb-sep" />

        <button
          type="button"
          className="aurora-tb-btn aurora-tb-picker-btn"
          onClick={() => setElementPickerOpen(true)}
          title="All HTML Elements Picker"
        >
          🧩 Elements...
        </button>

        <button
          type="button"
          className="aurora-tb-btn"
          onClick={() => setCommandPaletteOpen(true)}
          title="Command Palette (Ctrl+K)"
        >
          ⌘K
        </button>

        {overflowCommands.length > 0 && (
          <div className="aurora-tb-overflow-container" style={{ position: 'relative', marginLeft: 'auto' }}>
            <button
              type="button"
              className="aurora-tb-btn aurora-tb-overflow-btn"
              onClick={() => setIsOverflowOpen(!isOverflowOpen)}
            >
              •••
            </button>
            {isOverflowOpen && (
              <div className="aurora-tb-overflow-dropdown" style={{
                position: 'absolute',
                top: '100%',
                right: 0,
                background: 'white',
                border: '1px solid #cbd5e1',
                borderRadius: '6px',
                boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
                zIndex: 1000,
                minWidth: '160px',
                padding: '4px 0'
              }}>
                {overflowCommands.map((cmdId) => (
                  <button
                    key={cmdId}
                    type="button"
                    className="aurora-dropdown-item"
                    style={{
                      display: 'block',
                      width: '100%',
                      padding: '8px 12px',
                      border: 'none',
                      background: 'transparent',
                      textAlign: 'left',
                      cursor: 'pointer'
                    }}
                    onClick={() => {
                      setIsOverflowOpen(false);
                      exec(cmdId);
                    }}
                  >
                    {cmdId}
                  </button>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
