// packages/angular/src/editor.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnDestroy,
  OnInit,
  Output,
  ViewChild,
  forwardRef
} from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import {
  createEditor,
  type AuroraEditor,
  type EditorChange,
  type SelectionState,
  type ExportRequest,
  type CommandName,
  type HostUploadAdapter
} from '@aurora/editor';
import type { AuroraDocument } from '@aurora/model';
import { createToolbar, type ToolbarInstance } from '@aurora/ui';

@Component({
  selector: 'aurora-editor',
  template: `
    <div class="aurora-angular-container">
      <div *ngIf="toolbar" #toolbarContainer class="aurora-angular-toolbar"></div>
      <div #editorMount class="aurora-angular-editor-mount" role="textbox" aria-multiline="true"></div>
    </div>
  `,
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => AuroraEditorComponent),
      multi: true
    }
  ]
})
export class AuroraEditorComponent implements OnInit, OnDestroy, ControlValueAccessor {
  @Input() document?: AuroraDocument;
  @Input() toolbar: boolean = true;
  @Input() upload?: HostUploadAdapter;
  @Input() features?: unknown[];

  @Output() docChange = new EventEmitter<EditorChange>();
  @Output() selectionChange = new EventEmitter<SelectionState>();
  @Output() editorReady = new EventEmitter<AuroraEditor>();

  @ViewChild('editorMount', { static: true }) editorMountRef!: ElementRef<HTMLDivElement>;
  @ViewChild('toolbarContainer', { static: false }) toolbarMountRef?: ElementRef<HTMLDivElement>;

  private editor: AuroraEditor | null = null;
  private toolbarInstance: ToolbarInstance | null = null;
  private onModelChange: (value: AuroraDocument) => void = () => {};
  private onModelTouched: () => void = () => {};

  ngOnInit() {
    this.editor = createEditor({
      document: this.document,
      element: this.editorMountRef.nativeElement,
      upload: this.upload,
      features: this.features
    });

    if (this.toolbar && this.toolbarMountRef) {
      this.toolbarInstance = createToolbar({
        editor: this.editor,
        container: this.toolbarMountRef.nativeElement
      });
    }

    this.editor.on('change', (change) => {
      this.docChange.emit(change);
      this.onModelChange(change.document);
    });

    this.editor.on('selectionChange', (sel) => {
      this.selectionChange.emit(sel);
    });

    this.editor.on('blur', () => {
      this.onModelTouched();
    });

    this.editorReady.emit(this.editor);
  }

  ngOnDestroy() {
    this.toolbarInstance?.destroy();
    this.editor?.destroy();
    this.editor = null;
  }

  // ControlValueAccessor implementation
  writeValue(value: AuroraDocument | null): void {
    if (value && this.editor) {
      this.editor.setDocument(value);
    }
  }

  registerOnChange(fn: (value: AuroraDocument) => void): void {
    this.onModelChange = fn;
  }

  registerOnTouched(fn: () => void): void {
    this.onModelTouched = fn;
  }

  setDisabledState?(isDisabled: boolean): void {
    // Optionally toggle editable
  }

  // Imperative facade delegates
  getDocument(): AuroraDocument | undefined {
    return this.editor?.getDocument();
  }

  setDocument(doc: AuroraDocument): void {
    this.editor?.setDocument(doc);
  }

  execute(name: CommandName | string, input?: unknown) {
    return this.editor?.execute(name, input);
  }

  export(request: ExportRequest): string {
    return this.editor?.export(request) || '';
  }

  focus(): void {
    this.editor?.focus();
  }
}

// packages/react/src/editor.tsx
import React, { useEffect, useRef, useImperativeHandle, forwardRef } from 'react';
import { createEditor, type AuroraEditor, type EditorOptions, type EditorChange, type SelectionState, type ExportRequest, type CommandName } from '@aurora/editor';
import type { AuroraDocument } from '@aurora/model';
import { createToolbar, type ToolbarInstance } from '@aurora/ui';

export interface AuroraEditorProps {
  document?: AuroraDocument;
  onChange?: (change: EditorChange) => void;
  onSelectionChange?: (selection: SelectionState) => void;
  toolbar?: boolean;
  className?: string;
  style?: React.CSSProperties;
  editorOptions?: Omit<EditorOptions, 'document' | 'element'>;
}

export interface AuroraEditorRef {
  getDocument: () => AuroraDocument | undefined;
  setDocument: (doc: AuroraDocument) => void;
  execute: (name: CommandName | string, input?: unknown) => void;
  export: (request: ExportRequest) => string;
  focus: () => void;
  editor: AuroraEditor | null;
}

export function useAuroraEditor(options: EditorOptions = {}): AuroraEditor | null {
  const editorRef = useRef<AuroraEditor | null>(null);

  useEffect(() => {
    const editor = createEditor(options);
    editorRef.current = editor;

    return () => {
      editor.destroy();
      editorRef.current = null;
    };
  }, []);

  return editorRef.current;
}

export const AuroraEditorComponent = forwardRef<AuroraEditorRef, AuroraEditorProps>(
  function AuroraEditorComponent(props, ref) {
    const {
      document: initialDoc,
      onChange,
      onSelectionChange,
      toolbar = true,
      className = '',
      style,
      editorOptions
    } = props;

    const editorMountRef = useRef<HTMLDivElement>(null);
    const toolbarMountRef = useRef<HTMLDivElement>(null);
    const editorRef = useRef<AuroraEditor | null>(null);
    const toolbarRef = useRef<ToolbarInstance | null>(null);

    useImperativeHandle(ref, () => ({
      getDocument: () => editorRef.current?.getDocument(),
      setDocument: (doc) => editorRef.current?.setDocument(doc),
      execute: (name, input) => editorRef.current?.execute(name, input),
      export: (req) => editorRef.current?.export(req) || '',
      focus: () => editorRef.current?.focus(),
      editor: editorRef.current
    }));

    useEffect(() => {
      if (!editorMountRef.current) return;

      const editor = createEditor({
        ...editorOptions,
        document: initialDoc,
        element: editorMountRef.current
      });
      editorRef.current = editor;

      if (toolbar && toolbarMountRef.current) {
        toolbarRef.current = createToolbar({
          editor,
          container: toolbarMountRef.current
        });
      }

      const unsubChange = editor.on('change', (change) => {
        onChange?.(change);
      });

      const unsubSelection = editor.on('selectionChange', (sel) => {
        onSelectionChange?.(sel);
      });

      return () => {
        unsubChange();
        unsubSelection();
        toolbarRef.current?.destroy();
        toolbarRef.current = null;
        editor.destroy();
        editorRef.current = null;
      };
    }, []);

    return (
      <div className={`aurora-react-editor-container ${className}`.trim()} style={style}>
        {toolbar && <div ref={toolbarMountRef} className="aurora-react-toolbar-mount" />}
        <div ref={editorMountRef} className="aurora-react-editor-mount" role="textbox" aria-multiline="true" />
      </div>
    );
  }
);
